### ISSUE TITLE
arm64 builds?

### ISSUE THREAD

**Issue by refi64** [flathub/io.github.spacingbat3.webcord#3]
I noticed that [arm64 builds were explicitly disabled](https://github.com/flathub/io.github.spacingbat3.webcord/commit/51ec744879c3cb1fa63f035261e8dbc16b8fefed), why is that?

**Comment by orowith2os** [comment]
The manifest pulls a binary, rather than building from source here: https://github.com/flathub/io.github.spacingbat3.webcord/blob/master/io.github.spacingbat3.webcord.yml#L23
This might be able to be mitigated by pulling a different source using the only_arches option for aarch64, although that isn't very well documented currently, so I guess it makes sense that this manifest didn't include it.

**Comment by axtloss** [comment]
arm64 builds are currently disabled because Vega couldn't figure out how to build an arm64 tarball using GitHub actions, and I've admittedly never really looked into fixing that.
I could also just make the manifest extract an appimage that webcord directly offers, instead of building a custom tarball of it.

**Comment by axtloss** [comment]
I experimented with getting arm64 working, but the appimage and deb have an issue where the webcord logo on the start doesn't get loaded (when running outside or inside the flatpak) and I've had no luck with setting up the github ci to build an arm64 version of webcord as a tarball. 
I don't really want to ship a slightly broken version of webcord but if it's necessary to do it for arm builds I guess there is no other choice

**Comment by axtloss** [comment]
I modified the manifest to use the appimage distributed by webcord directly and enabled aarch64 builds, it should be available to install soon. Although i can't really test if the aarch64 version will properly work since I have no way of testing it.

**Comment by refi64** [comment]
I can confirm it's working on my arm64 device, thanks!

**Comment by AzureRaptor** [comment]
Using it via flatpak on arm64 Pi 4 - thank you _very_ much for this build!
