### ISSUE TITLE
Crashing when re-opening window on Wayland

### ISSUE THREAD

**Issue by BuonHobo** [flathub/io.github.spacingbat3.webcord#6]
I'm just copy-pasting the issue that I found here https://github.com/SpacingBat3/WebCord/issues/240
I'm experiencing this and apparently it's a problem on the flatpak side. I suggest looking at the actual conversation over there.

**Comment by axtloss** [comment]
This doesn't seem like a flatpak issue from what the comments in that issue say, but I have completely reverted the wayland by default for now, I'll enable it again when webcord wayland becomes more stable.

**Comment by SpacingBat3** [comment]
@BuonHobo It isn't an issue specific to Flatpaks, but there're a few issues in Flapaks like lack of access to secure daemon (WebCord uses it to prevent manipulations of some of its files, maybe it's even used internally in Electron to encrypt some files produced by Chromium engine) I've found there in produced logs. @axtloss maybe you should take a look on it to fix some problems with the sandboxing.

**Comment by axtloss** [comment]
The dbus errors that I've seen, except for the `secret service operation failed` error, aren't really relevant, for some reason webcord/electron wants to access the whole session and system bus, but giving access to the whole system/session bus isn't recommended by flatpak/flathub, which is why I won't do that.

As for the secrets issue, this is due to the flatpak not having acess to `org.freedesktop.Secrets`, I'll give it access to that.
