### ISSUE TITLE
Maximizing the window when the app opens

### ISSUE THREAD

**Issue by RaptaG** [flathub/io.github.spacingbat3.webcord#89]
Thanks a lot for packaging the app for Flathub!

**Comment by SpidFightFR** [comment]
Hey, because of many problems related to restoring the previous window settings (that's not a flatpak issue, the base client has it as well), we added a setting to remove `$HOME/.var/app/io.github.spacingbat3.webcord/config/WebCord/windowState.json`, it restores the client to a default "tiny" window at every startup.

What you could do is make use of kwin integrated "script" to automatically maximize webcord on startup.
